# Generated by Django 3.2.5 on 2021-07-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='NameId',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='ReservationDayId',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='ReservationHourId',
        ),
        migrations.AddField(
            model_name='reservation',
            name='ReservationDay',
            field=models.CharField(default='Today', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='ReservationHour',
            field=models.CharField(default=9, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
