# Generated by Django 3.2.5 on 2021-07-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0005_auto_20210715_2124'),
    ]

    operations = [
        
    ]
